PREFIX orth: <http://purl.jp/bio/11/orth#>
PREFIX hop: <http://purl.org/net/orthordf/hOP/ontology#>

SELECT ?description ?symbol
WHERE {
    ?gene a orth:Gene ;
          hop:symbol ?symbol ;
	  hop:description ?description .
}
