PREFIX orth: <http://purl.jp/bio/11/orth#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX hop: <http://purl.org/net/orthordf/hOP/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (max(?id) as ?max_id)
WHERE {
  ?group a orth:OrthologGroup ;
      orth:organism ?organism .
  ?organism rdfs:label ?label ;
      dct:identifier ?id .
}
